### ISSUE TITLE
Giant Goddess Subtitle zooms away

### ISSUE THREAD

**Issue by ThatCuteEevee** [deviant-dev/dominatrix-simulator-issues#123]
**Describe the issue**
   When the player looks up the Goddess Subtitle moves to the players eyelevel up to where the Giant Goddess's head is

**Screenshots**
  - See video posted on discord channel Playtest-feedback

**To Reproduce**
 - Play through intro Goddess Scene and get to the end with Giant Goddess with subtitles on, then look up  

**Expectations**
   - The subtitle should not zoom up as it may make it un-readable by the player

**System Info(please complete the following information):**
 - Desktop
 - Version: 2.1.0+122

**Additional context**

**Comment by Lewder** [comment]
Seems to be fixed in build 124. The subtitles follow under the Goddess' head, unless the player looks away in which case they follow the camera.
