### ISSUE TITLE
Head Tracking for Ass Play

### ISSUE THREAD

**Issue by DevilishDomina** [deviant-dev/dominatrix-simulator-issues#124]
**Describe what you'd like**
Fans are asking for some ass play.
Suggestions include having tempo minigame that guides the player through riding a dildo or other stationary anal toy.

Fun positions - riding a dildo mounted to the floor or worn by a Mistress (up and down movement), riding a dildo attached to a vertical surface (back and forth movement)

**Comment by HeadphoneTaco** [comment]
Closing due to Cunnilingus minigame prototype
