### ISSUE TITLE
Foot Worship Scenes

### ISSUE THREAD

**Issue by DevilishDomina** [deviant-dev/dominatrix-simulator-issues#125]
**Describe what you'd like**
Fans would like to see more foot fetish content. 

From fan:
More bare feet with painted to nails would be great in general. Personally, scenes involving forced foot worship, trampling, or foot smelling would be awesome! Foot worship as a reward for following instructions would be pretty cool as well. 

**Additional details**
Ooh, also [...] would be fun because [...].

**Comment by HeadphoneTaco** [comment]
Closing due to Foot Fetish content existing in game
