### ISSUE TITLE
Rotating Fire

### ISSUE THREAD

**Issue by Lewder** [deviant-dev/dominatrix-simulator-issues#126]
**Describe the issue**
Fire in sconce tracks player view, resulting in weird clipping and rotating fire.

**Screenshots**
![Rotating Fire](https://user-images.githubusercontent.com/70164228/109581714-c9a5c980-7aca-11eb-8a4d-175cf2d49de5.jpg)

**To Reproduce**
1. Look at the fire in the main game loop.
2. Rotate your head.

**Expectations**
Would expect that fire would remain level with the sconce, not the player's view.

**System Info(please complete the following information):**
Valve Index
Build 124

**Comment by HeadphoneTaco** [comment]
Closing due to #10
