### ISSUE TITLE
Overlapping text at end of tutorial

### ISSUE THREAD

**Issue by Lewder** [deviant-dev/dominatrix-simulator-issues#127]
**Describe the issue**
Overlapping text at end of tutorial when Ms. Treatment shows all of the options to follow the game.

**Screenshots**
![Overlapping text](https://user-images.githubusercontent.com/70164228/109582462-379ec080-7acc-11eb-90d8-b96a8fda0adc.jpg)

**To Reproduce**
1. Reach end of tutorial

**Expectations**
If I recall, these should be two separate buttons? Or a button and a logo?

**System Info(please complete the following information):**
Valve Index
Build 124

**Comment by Lewder** [comment]
Appears to be fixed as of build 129:
https://cdn.discordapp.com/attachments/282314667781521408/820652789407285258/20210314004819_1.jpg

**Comment by ThatCuteEevee** [comment]
Confirmed resolved in 2.1.0+139. Resolving
