### ISSUE TITLE
Dominatrix simulator.EXE keeps file deleting it self

### ISSUE THREAD

**Issue by BloodRaven13** [deviant-dev/dominatrix-simulator-issues#128]
Whenever I run Dominatrix simulator shortly after the EXE deletes itself
![DOM EXE proof](https://user-images.githubusercontent.com/79926640/109675010-a0218800-7b34-11eb-9a91-9215b716ce99.jpg)

**Comment by deviant-dev** [comment]
Thank you for the bug report!

Do you have any antivirus software running? I'm wondering if something like
that is mistaking the game for malware and 'quarantining' the .exe?

I'd so, try downloading it again and disabling the antivirus/malware
software before you run and see if it stays around.

**Comment by Lewder** [comment]
For what it's worth, VirusTotal show the main Steam DomSim executable at 0/70 detections. Of course, heuristic or behavioral analysis might have had a false positive.

**Comment by ThatCuteEevee** [comment]
Unable to replicate issue, no response from player for additional information. Closing.
