### ISSUE TITLE
Difference in view points.

### ISSUE THREAD

**Issue by VexLight** [deviant-dev/dominatrix-simulator-issues#129]
Look Dominatrix's can be fun but pushy b*&^%s are still pushy b^&$%s. For me someone softer and more respectful before the play begins would be better

**Describe what you'd like**
Tell us your deepest, darkest desires.
Be clear, and concise.
Ex. I really would enjoy [...].
Reference other reports by using **#**, a dropdown menu will appear.

**Additional details**
Ooh, also [...] would be fun because [...].

**Comment by HeadphoneTaco** [comment]
Can you please elaborate on this? What scene did you feel that being a pushy bitch was inappropriate?

**Comment by deviant-dev** [comment]
We've added added Ms Treatment who has a much softer Domme style.
