### ISSUE TITLE
Feminine appearance causes inconsistent voice lines

### ISSUE THREAD

**Issue by Lewder** [deviant-dev/dominatrix-simulator-issues#130]
**Describe the bug**
Nega Yuki and Head Mistress will refer to the body part as a "cock" in voice lines even when subtitles refer to it as a slit.

**To Reproduce**
Select feminine appearance / girl. Play through the tutorial starting around where Nega Yuki first appears.

**Expected behavior**
Expect voice lines to match subtitles. 

**System Info(please complete the following information):**
 - Valve Index
 - Build 124

**Comment by Lewder** [comment]
Seems to be fixed as of build 129, at least in all tutorial scenes which are what I tested each time.

**Comment by ThatCuteEevee** [comment]
Issue confirmed to be resolved in 2.1.0+139. Closing
