### ISSUE TITLE
Head Mistress' teeth darker than they should be

### ISSUE THREAD

**Issue by Lewder** [deviant-dev/dominatrix-simulator-issues#131]
**Describe the issue**
Lighting on HM's teeth makes it appear as though there's a gap. I thought it was just me, but my friend demoed the game today and asked whether HM had a chipped tooth, even though she didn't know that I had thought the same thing.

**Screenshots**
Unable to upload. Will attempt again to show what I mean.

**To Reproduce**
Play through HM's scene in the tutorial. Just the beginning where she asks whether the player knows who she is etc.

**Expectations**
Make the teeth just a little bit more reflective.

**System Info(please complete the following information):**
 - Valve Index
 - Build 124

**Comment by Lewder** [comment]
Can't upload to Github. Links provided instead:
https://cdn.discordapp.com/attachments/534377811104890899/817986222789623838/20210301192144_1_edit.jpg
https://cdn.discordapp.com/attachments/534377811104890899/817986224706420786/20210301192139_1_edit.jpg

**Comment by HeadphoneTaco** [comment]
Closing due to #10
