### ISSUE TITLE
Posing issues for shorter players

### ISSUE THREAD

**Issue by Lewder** [deviant-dev/dominatrix-simulator-issues#132]
**Describe the bug**
Let a friend demo my copy of the game today. They ran into a lot of issues with the standing poses. e.g.  

- Yuko Onna's tutorial scene where you must beg for attention like a puppy: They needed to hold their hands up nearly over their head.
- HM's tutorial scene where you must stand at attention with your chin up: They needed to hold their chin up higher than was reasonable.
- HM's tutorial scene where you must present your wrists: They had to hold their wrists higher than was reasonable, nearly level with head.

**To Reproduce**
Play through Yuki Onna and HM's tutorial scenes.

**Expected behavior**
It's expected that the model used to figure out where the player is holding their limbs would scale with player height. Some folks on the Discord server seem to have similar issues.

**System Info(please complete the following information):**
 - Valve Index
 - Build 124

**Comment by HeadphoneTaco** [comment]
Closing due to #181
