### ISSUE TITLE
JOI Content

### ISSUE THREAD

**Issue by Lewder** [deviant-dev/dominatrix-simulator-issues#133]
**Describe what you'd like**
JOI content could be offered as a reward from any and all mistresses. 

1. Scene begins where mistress says what is expected of the player
2. Player may be asked whether they have a certain prop they can use e.g. cock ring, dildo, plug, vibrator, ice cube, etc.
3. A (few) random modifier(s) might be selected e.g. non-dominant hand, stand, kneel, sit, etc.
4. Main loop begins. The following things repeatedly happen at random until a target is met:
- Player may be asked to touch themself in a certain way. Some kind of hand motion or audio beat will allow the player to track their strokes.
- Player may be asked to strike themself in a certain way. Hand motion or audio beat will show them how often to slap/spank/etc.
- Random modifiers may change. i.e. You must kneel now.
- Player may be asked to use the prop they said they had ready. i.e. Put on the cock ring.
- (Only near the middle to end of a session) Player may be asked to edge.
5. The mistress will now instruct you how to finish: Any combination of full or ruined / normal or eaten.

**Comment by HeadphoneTaco** [comment]
Closing due to JOI content existing in game
