### ISSUE TITLE
Appearance selection statues do not allow advancement

### ISSUE THREAD

**Issue by Lewder** [deviant-dev/dominatrix-simulator-issues#134]
**Describe the bug**
Selecting appearance using the statues does not advance the story.

**To Reproduce**
1. Play through beginning of tutorial
2. Select masculine or feminine appearance
3. You will not be prompted to move to the next scene
4. Required that you make your selection through the journal before the option is given

**Expected behavior**
Expect the "move" option to appear after selecting the statue

**Screenshots**
https://cdn.discordapp.com/attachments/660917480968945673/820650371604676608/20210314000812_1.jpg
https://cdn.discordapp.com/attachments/660917480968945673/820650466470920202/20210314000827_1.jpg
https://cdn.discordapp.com/attachments/660917480968945673/820650625829961728/20210314000836_1.jpg

**System Info(please complete the following information):**
 - Valve Index
 - Build 129

**Comment by deviant-dev** [comment]
I'm not seeing this issue in the latest, so moving this to validate.

**Comment by HeadphoneTaco** [comment]
Confirm, issue is not present as of Ver 2.1.0. Closing Bug.
