### ISSUE TITLE
Crying sound effect persists through creation of new profile

### ISSUE THREAD

**Issue by Lewder** [deviant-dev/dominatrix-simulator-issues#135]
**Describe the bug**
Needed to start a new profile to test the latest build. Was surprised when the crying sound effect persisted through the first scene of the tutorial.

**To Reproduce**
1. Load a save at the beginning of HM's intro scene where the sub is crying.
2. Delete a profile and start a new game.
3. Game won't actually start until you close the journal iirc.
4. HM's music and crying persist until the first tutorial music starts playing.
5. But then the music is correct, but the crying and pleading can still be heard.

**Expected behavior**
Expect all music and sound effects from a scene to stop when you load a new profile or start a new one.

**Screenshots**
https://cdn.discordapp.com/attachments/282314667781521408/820651650649817177/20210314000617_1.jpg

**System Info(please complete the following information):**
 - Valve Index
 - Build 129

**Comment by deviant-dev** [comment]
Ambient and music are now reset when starting the game and I'm not able to reproduce this in the latest build.

**Comment by ThatCuteEevee** [comment]
Confirmed issue is still occurring, additional notes to be found in closed issue #188

**Comment by HeadphoneTaco** [comment]
Keeping report open, as status of bug is unknown

**Comment by HeadphoneTaco** [comment]
Hey @Lewder is this issue still valid?

**Comment by HeadphoneTaco** [comment]
Closing due to lack of response on both Github and Discord
