### ISSUE TITLE
Move: treat intro does not work as expected

### ISSUE THREAD

**Issue by ThatCuteEevee** [deviant-dev/dominatrix-simulator-issues#137]
**Describe the bug**
  - when continuing after playing the demo, Ms. Treatment will be in the middle of the hall but no spot to select to continue. When selecting the spot through the journal the player is then teleported in the middle of Ms. Treatment's door. Ms. Treatment will then start to go through her lines as if the player is in front of her

**To Reproduce**
 - complete into
 - Chose continue
 - select "Move: treat intro" in the journal

**Expected behavior**
  - there should be a move-to spot in front of Ms. Treatment and the command should bring the player to be in front of Ms. Treatment during the scene

**Screenshots**
![20210511104413_1](https://user-images.githubusercontent.com/60497088/117837787-bd1abb80-b247-11eb-8840-f94e986ae289.jpg)
![20210511104421_1](https://user-images.githubusercontent.com/60497088/117837810-c0ae4280-b247-11eb-945f-04ef3c2e8be5.jpg)
![20210511104429_1](https://user-images.githubusercontent.com/60497088/117837823-c3a93300-b247-11eb-86ec-a2c5e9099aa5.jpg)
![20210511104435_1](https://user-images.githubusercontent.com/60497088/117837862-cc9a0480-b247-11eb-8dd8-50e2aad96200.jpg)

**System Info(please complete the following information):**
 - VR Device: Full Valve index system
 - Version: 2.1.0+139

**Additional context**

**Comment by ThatCuteEevee** [comment]
The following errors show up in the log when going through the Ms. Treatment intro after doing the main game intro:
  - Couldn't find translation ID for Move:treatIntro (expected 'MOVE_TREATINTRO')
 
After clicking on the journal entry in order to continue (where it will transport the player in the middle of the door for Ms. Treatment's room), the following errors pop up
 - Couldn't find translation ID for Move:treatIntro (expected 'MOVE_TREATINTRO')
 - Physics.simulate(...) was called but out simulation is active. You should disable auto simulation first before calling this function therefore the simulation was not run

Secondary note: After doing a scene with a Mistress to Serve there was a second visit from Ms. Treatment, in which the approach spot was available to stand infront of her that does work as expected, but the Couldn't find translation ID for Move:treatIntro (expected 'MOVE_TREATINTRO') message shows up 3 times in a row before showing line SC: Current choices: move:Approach

**Comment by HeadphoneTaco** [comment]
Issue appears to be fixed, same with the issue of loading into the floor from #142 
@Ropelopunny can you confirm?

**Comment by ThatCuteEevee** [comment]
Confirmed issue resolved, closing
