### ISSUE TITLE
Nega Yuki - boot edging scene loops

### ISSUE THREAD

**Issue by ThatCuteEevee** [deviant-dev/dominatrix-simulator-issues#139]
**Describe the bug**
   During Nega Yuki scene, if the player rolls two cups one blank and gets the boot edging scene the scene just continuously loops with no end scene

**To Reproduce**
 - Play the Nega Yuki Scene
 - Roll two cups and one blank
 - get the edge to Nega Yuki's boots scene

Repeated lines:
  - You're oozing at the sight of my boots, aren't you whore?" - Yes
  - "do you enjoy bing my foot slut?" - Yes
  - "You love edging to my boots, don't you bitch?" - Yes
  - there were two points in which she asked me if I was going to cum, the answer was yes in both instances and she gave a line that she was the only one allowed to cum. After 15 min

**Expected behavior**
 The scene should not loop and the scene eventually will end.

**Screenshots**
N/A

**System Info(please complete the following information):**
 - VR Device: Desktop
 - Version: 2.1.0+139
 - Voice: feminine
 - Physique: Feminine
 - Designation: Girl
 - Genitals: Vagina

**Additional context**

**Comment by HeadphoneTaco** [comment]
The scene does end in current version (2.1.0), moving to Validate

**Comment by HeadphoneTaco** [comment]
Closing due to lack of repeatability
