### ISSUE TITLE
Miss Treatment model issue

### ISSUE THREAD

**Issue by JackReven669** [deviant-dev/dominatrix-simulator-issues#140]
**Describe the issue**
Miss Treatment's Therapy model has a bit of her body not attached. it is floating under her foot 

**Screenshots**
![OculusScreenshot1623328958 (2)_LI](https://user-images.githubusercontent.com/85486378/121527711-5280ab00-c9c0-11eb-93c4-1ea827e2e601.jpg)

**To Reproduce**
1. Go to 'Miss treatment's room'
2. Choose 'any of the Theriputic Domming sessions'
3. Try to 'look at her feet'

**Expectations**
Describe what you expected to see.

**System Info(please complete the following information):**
 - VR Device: Oculus Quest 2
 - Version: 2.1.0+139

**Additional context**

**Comment by HeadphoneTaco** [comment]
That's the tip of her tail! Due to the way she's laying down, the majority of her tail is clipping through the surface. It's a minor cosmetic issue, going to close it. Thank you for taking the time to fill out a report! :)
