### ISSUE TITLE
Long scene titles running off the journal pages

### ISSUE THREAD

**Issue by ThatCuteEevee** [deviant-dev/dominatrix-simulator-issues#141]
**Describe the issue**
  If in or going back to a save in which the player is in the Nega Punishment hard Genital Torture scene, the title of the scene when in the journal looking at profile info, the text runs off the pages of the journal 

**Screenshots**
![Screenshot (6)](https://user-images.githubusercontent.com/60497088/121553313-29bbde00-c9df-11eb-8d16-f16fd9ba1d5b.png)

**To Reproduce**
  open up the journal and check the profile either during the scene or when going back to a profile that is still in that scene

**Expectations**
 - For the text to stay on the pages of the Journal

**System Info(please complete the following information):**
 - VR Device: Mouse and keyboard
 - Version: +143

**Additional context**

**Comment by HeadphoneTaco** [comment]
Closing due to rarity of bug
