### ISSUE TITLE
Player loads into floor when starting Ms. Treatment intro

### ISSUE THREAD

**Issue by ThatCuteEevee** [deviant-dev/dominatrix-simulator-issues#142]
**Describe the issue**
   When starting the intro for Ms. Treatment intro scene, after the end of the giant Goddess punishment scene, the player loads into the floor of the stair case

**Screenshots**
![Screenshot (2)](https://user-images.githubusercontent.com/60497088/121554691-5b817480-c9e0-11eb-8e39-9f6b5a30d19a.png)

![Screenshot (8)](https://user-images.githubusercontent.com/60497088/121555080-b2874980-c9e0-11eb-8b85-523834572459.png)

**To Reproduce**
  Complete the DomSim intro and begin the Ms. Treatment intro

**Expectations**
   The player should be ontop of the floor not in the middle

**System Info(please complete the following information):**
 - VR Device: Mouse and keyboard
 - Version: +143

**Additional context**
  Player does appear in front of Ms. Treatment and the move position does show and work, moving the player to the correct position directly in front of her.

**Comment by HeadphoneTaco** [comment]
Issue appears to be fixed in latest, moved to Validate

**Comment by ThatCuteEevee** [comment]
Confirmed issue is resolved, closing
