### ISSUE TITLE
HM Slave Sunk Desk

### ISSUE THREAD

**Issue by HeadphoneTaco** [deviant-dev/dominatrix-simulator-issues#148]
**Describe the bug**
During the slave spanking scene in HM's intro, the slave is partially
![slave_desk](https://user-images.githubusercontent.com/12089633/121749876-a2e33000-cac8-11eb-9d7a-fde2a9874041.png)
 sunk into the desk.

**Screenshots**

**System Info:**
 - VR Device: HTC Vive 1st Gen
 - Version: 2.1.0+143

**Comment by deviant-dev** [comment]
Looks like this was fixed along with the broken animations in the Goddess intro

**Comment by HeadphoneTaco** [comment]
Sweet, that darn umotion project reached too far lol

**Comment by HeadphoneTaco** [comment]
Confirmed, closing bug.
