### ISSUE TITLE
HM Slave Spank Extra

### ISSUE THREAD

**Issue by HeadphoneTaco** [deviant-dev/dominatrix-simulator-issues#149]
**Describe the bug**
When HM is spanking the slave during her intro scene, the slave reacts to a spank that HM isn't performing.

**System Info:**
 - VR Device: HTC Vive 1st Gen
 - Version: 2.1.0+143

**Comment by HeadphoneTaco** [comment]
Issue appears to be fixed, moving to validate.

**Comment by ThatCuteEevee** [comment]
confirmed issue resolved, closing
