### ISSUE TITLE
HM Spank Rest

### ISSUE THREAD

**Issue by HeadphoneTaco** [deviant-dev/dominatrix-simulator-issues#154]
**Describe the bug**
When HM is spanking the player 10 times during the intro, the rest is nonexistent. She tells the player to rest back on their heels, but when the player gets into position, she instantly tells the player to stand up.

**System Info:**
 - VR Device: HTC Vive 1st Gen
 - Version: 2.1.0+143

**Comment by HeadphoneTaco** [comment]
Modified Ink to allow the player a 3 second wait, moving to validate

**Comment by ThatCuteEevee** [comment]
Verified issue is resolved, closing
