### ISSUE TITLE
Ms T Therapy Submissive Headspace Lookat

### ISSUE THREAD

**Issue by HeadphoneTaco** [deviant-dev/dominatrix-simulator-issues#174]
**Describe the bug**
Ms T doesn't look at the player correctly. She does look at the player properly before you select Submissive Headspace.

**System Info:**
 - VR Device: HTC Vive 1st Gen
 - Version: 2.1.0+143

**Comment by deviant-dev** [comment]
@HeadphoneTaco I wasn't able to reproduce this problem. The `Hell.Ready` scene also seems to be set up correctly. Here she is looking at me directly:
![image](https://user-images.githubusercontent.com/33731102/121795284-731c5f80-cc63-11eb-9601-9577b2c1d2fa.png)

Do you have any specific steps to reproduce this one?

**Comment by HeadphoneTaco** [comment]
I was bobbing around, crouching and such. Will have to re-examine and see if it's reproduceable on next build.

**Comment by ThatCuteEevee** [comment]
Confirmed to still be an issue in current build. Miss T will stare forward and not stare down at the player when kneeling. 2.1.0+145

**Comment by asphyxiachan** [comment]
Ms. T looks at me during the Submissive Headspace scene during the "look at me" part of the script. Kneeling or otherwise (Journal reads 2.1.1, htc vive original)

**Comment by HeadphoneTaco** [comment]
Closing due to irrelevance at this present time
