### ISSUE TITLE
Mistress Yuki points in the wrong direction during tutorial

### ISSUE THREAD

**Issue by kisatan** [deviant-dev/dominatrix-simulator-issues#183]
**Describe the issue**
During the intro when Yuki tells you to go to the Headmistress she points in the wrong direction, towards Enforcer Furia's room, where the waypoint for Headmistresses room used to be.
If you talk to Yuki again before reporting to the Headmistress she will point in the correct direction.

**To Reproduce**
1. Play the intro until Yuki instructs you to visit the Headmistress for punishment training.
2. Observe Yuki pointing to the left (her right) 

**Expectations**
Yuki should be pointing to the right (her left) where the updated location of Headmistresses room is

**System Info(please complete the following information):**
 - VR Device: Oculus Quest 2 (wired connection)
 - Version: Dominatrix Simulator v.2.1.0+145@d0b6540 (according to ingame Journal)

**Comment by HeadphoneTaco** [comment]
Updated Ink script to make Yuki point in the correct direction, closing.
