### ISSUE TITLE
Goddess lips not syncing and no animations when loading intro scene

### ISSUE THREAD

**Issue by ThatCuteEevee** [deviant-dev/dominatrix-simulator-issues#184]
**Describe the bug**
  If in a scene on a different profile, then switch to a profile that has the Goddess intro scene loaded, the Goddess's lips do not move at all to the voice lines, and the only animation that plays is the idle stance animation

**To Reproduce**
 1) Start on any other profile that is that has a scene loaded, the scene does not have to be started, just having it loaded is enough
 2) load the profile in which the Goddess intro scene is loaded
 3) Once loaded The goddesses lips will not move to the voice line and none of the normal animations will play

**Expected behavior**
  For the Goddesses lips to sync with the voice lines after loading the profile from another scene

**Screenshots**

**System Info(please complete the following information):**
 - VR Device: mouse and keyboard
 - Version: 2.1.0+145

**Additional context**
   Work around: exit the game under the profile you want to play under, open DomSim back up to reload the scene

 - This was tested from loading the post intro Ms. Treatment, Head Mistress, and Enforcer Furia's scenes. No other scenes have been tested to see if it replicates the issue. Did test to see if the issue would occur in other scenes, so far I have not found any other scenes in which it occurs, will update bug if any other instances are found.

**Comment by HeadphoneTaco** [comment]
@Ropelopunny Have you encountered this bug again, since june?

**Comment by HeadphoneTaco** [comment]
Closing, as this issue is old, and likely resolved in newer builds
