### ISSUE TITLE
Leg Collision in Yuki Cunnilingus Scene #2

### ISSUE THREAD

**Issue by rockanrolla** [deviant-dev/dominatrix-simulator-issues#192]
**Describe the bug**
In the beginning of the scene, during the introduction, Yuki's legs are colliding with the couch.

**To Reproduce**
1. Play the scene

**Expected behavior**
Her legs should not be colliding with the couch.

**Screenshots**
![Yuki Leg Collision](https://user-images.githubusercontent.com/69108705/132613130-276d16e3-4660-4161-a7b5-953b82409a58.jpg)
![Yuki Leg Collision1](https://user-images.githubusercontent.com/69108705/132613131-5c0f7050-3871-4fcb-8df9-0db89687add9.jpg)

**System Info(please complete the following information):**
 - VR Device: Desktop, keyboard & mouse
 - Version: 2

**Additional context**
N/A

**Comment by HeadphoneTaco** [comment]
Closing due to lack of further user complaints
