### ISSUE TITLE
Nega Dice Roll visual doesn't match what she says you rolled

### ISSUE THREAD

**Issue by rockanrolla** [deviant-dev/dominatrix-simulator-issues#194]
**Describe the bug**
Found a bug playing the latest version, 2.1.1.+147, on Desktop. I was able to recreate it twice. Went to Visit Nega for a reward. We rolled the dice and, although the dice showed three skulls, she said "Two cups and a blank". The second time the dice showed Two skulls and a blank and she said "Cup and skull cancel each other out" as if I had rolled a cup, skull, and a blank.

**To Reproduce**
1. Go visit Nega-Yuki
2. Roll Dice

**Expected behavior**
The dice visuals should match what Nega-Yuki says

**System Info(please complete the following information):**
Playing on Desktop with mouse and keyboard

**Comment by HeadphoneTaco** [comment]
Closing due to irrelevance at this present time
