### ISSUE TITLE
Not able to get punishment stones

### ISSUE THREAD

**Issue by Petruchio101** [deviant-dev/dominatrix-simulator-issues#199]
This is a problem across the whole game, where I was unable to get punishment stones from any domme.  Below is an example repro for Yuki--other dommes provided similar results.

Running 2.1.1; one run through (haven't restarted), issue has been in place from beginning of this run.

-----

So, I got to the point where she asked me to sit, and I tried shaking my head but it wouldn't register.  She just kept asking for me to sit, although she cycled through I think four different phrases.

So I sat.  She was happy. :slight_smile:

Then when she asked me if I understood, I gave the no pose.  Multiple times,  Again, she just kept trying, until I said yes.

Once you get past that, she no longer checks for yes or no with either the head or the yes/no pose. So I tried ignoring her requests.  I also tried looking away for an extended period to see if I'd get admonished for not paying attention.  I didn't get that either.
If I say no to a reward, then no to a task, I found that I just get sent back to the lobby.

**Comment by HeadphoneTaco** [comment]
Closing due to lack of further user complaints
