### ISSUE TITLE
Test_HeadphoneTaco

### ISSUE THREAD

**Issue by michaelhardwicke** [deviant-dev/dominatrix-simulator-issues#2]
Heyo Deviant, just testing to see if this goes through.
![8065_hyperblobsweat](https://user-images.githubusercontent.com/12089633/73514283-5ce36b80-43ae-11ea-8825-8efa209b6283.png)

**Comment by deviant-dev** [comment]
Looks like it works well!

**Comment by HeadphoneTaco** [comment]
Yes, this test was indeed a triumph.
Where's the cake?
