### ISSUE TITLE
Body Type Not Matching Journal Selection

### ISSUE THREAD

**Issue by DevilishDomina** [deviant-dev/dominatrix-simulator-issues#204]
**Describe the bug**

Player on Steam reports that in the current build, the game is not correctly selecting the body type to correspond with the journal choices:

"From Domina: Your submissive can definitely play as female and select the name 'girl' and 'vagina'. The game will treat her and refer to her as a girl.

From Player: There is a bug in the rcecent version related to this! If we choose the 'Female' designation, even if the male body is sellected, our model shown on screen is Female!"

**To Reproduce**

Set up the character to 'female' designation with a 'male' body. See if the body / genitals shown on screen are male or female. 

**Expected behavior**

Should be male (not including genitals).

**Comment by HeadphoneTaco** [comment]
> Set up the character to 'female' designation with a 'male' body. See if the body / genitals shown on screen are male or female.

Where is this "shown on screen" coming in? Is the player talking about the gender select statues before meeting Goddess in the tutorial? When Nega gropes the player in Yukis' intro?

**Comment by DevilishDomina** [comment]
They did not specificy, but it is related to the latest release, which includes the new Goddess Reward Serviced. That is the scene where you lay on your back and one of her slaves masturbates you. A body avatar is shown in that scene.

**Comment by Sonny3412** [comment]
Can confirm this bug no longer happens.
You can now select bodies, penis and vagina and the game dynamically change the scene.

**Comment by ThatCuteEevee** [comment]
Sonny confirmed the issue no longer occurs, closing
