### ISSUE TITLE
Ms T Slide After Minigame

### ISSUE THREAD

**Issue by HeadphoneTaco** [deviant-dev/dominatrix-simulator-issues#230]
**Describe the bug**
Ms T slides over a bit, after her Cunnilingus minigame is finished, and intersects with her chair.
Doesn't happen immediately, the slide occurs once she asks the player if they orgasmed.

**Screenshots**

![Ms_T-Seat_Shift](https://user-images.githubusercontent.com/12089633/144962292-8c1df9e2-80f1-4732-8392-06173b8d7bd8.png)

**System Info(please complete the following information):**
 - Version: 2.2.0

**Comment by Sonny3412** [comment]
Just reproduced it, it's not huge but it's definitely fixable.
![Screenshot ](https://user-images.githubusercontent.com/123605940/214765654-6abc59ab-5fb5-434e-839e-44a1e844ebda.png)

**Comment by ThatCuteEevee** [comment]
Tested in 2.6.0+176 - unable to replicate. Resolving
