### ISSUE TITLE
Headmistress Pronoun Usage

### ISSUE THREAD

**Issue by HeadphoneTaco** [deviant-dev/dominatrix-simulator-issues#239]
S.A.M.#6969
January 1, 2022

OH, so, small thing, Could someone check for things like the Headmistresses' first reward (the mandatory one) and see if they can change the part where she calles the player a 'manwhore' to the female one. I'm trans feme so I have my set up as Pet, Feminine body, but with a penis, and I made sure it was that way before this happened, and I'd like to be degraded being called feminine things.

**Comment by ThatCuteEevee** [comment]
Tested issue in V2.5.1+169, unable to replicate issue. Closing
