### ISSUE TITLE
Head mistress intro scene

### ISSUE THREAD

**Issue by JackReven669** [deviant-dev/dominatrix-simulator-issues#253]
**Describe the bug**
During the Headnistress intro scene, the Headmistress is far forward, meaning she is nowhere near the slave as she swats her

**To Reproduce**
1. Go to headmistress intro scene
2. See error

**Expected behavior**
on any other update, she is positioned correctly next to the slave

**Screenshots**

**System Info(please complete the following information):**
 - VR Device: Occulus Quest 2 connected via cable
 - Version: 2.7.0+179
**Additional context**

**Comment by JackReven669** [comment]
Video Evidence of bug  https://www.dropbox.com/s/24tgzxwulwki8t7/Headmistress%20intro.mp4?dl=0

**Comment by HeadphoneTaco** [comment]
Fix has been implemented, closing issue
