### ISSUE TITLE
Miss Treatment riding reward

### ISSUE THREAD

**Issue by JackReven669** [deviant-dev/dominatrix-simulator-issues#254]
**Describe the bug**
Miss treatment's riding reward does not take a bloodstone as it should

**To Reproduce**
1. Go to Miss Treatment when you have rewards
2. Choose reward (hopefully get riding scene)

**Expected behavior**
Bloodstones should be used for rewards

**Screenshots**

**System Info(please complete the following information):**
 - VR Device: Oculus Quest 2 connected via cable
 - Version: 2.7.0+179

**Additional context**

**Comment by JackReven669** [comment]
Video Evidence of Bug: https://www.dropbox.com/s/nu5xajihikqegzn/Riding%20scene.mp4?dl=0

**Comment by HeadphoneTaco** [comment]
Thank you! Fix implemented, closing issue
